name: flutter_loggy_dio
description: Extension for loggy. Includes interactor and pretty printer for Dio.
version: 3.1.0
repository: https://github.com/infinum/flutter-logger
homepage: https://github.com/infinum/flutter-logger

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  loggy: ^2.0.3
  dio: ^5.0.0

dev_dependencies:
  lints: ^3.0.0
