name: flutter_loggy
description: Loggy extension to use 'developer.log' with pretty printer in Flutter
version: 2.0.3+1
repository: https://github.com/infinum/flutter-logger
homepage: https://github.com/infinum/flutter-logger

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  loggy: ^2.0.3

dev_dependencies:
  flutter_lints: ^5.0.0
